### PR TITLE
Upgrade hetmatpy with p-value imprecision fix

### PR DESCRIPTION
**Pull request by dhimmel**
Refs https://github.com/greenelab/hetmech/issues/153

### CODE REVIEW

**Comment by dhimmel** [comment]
@dongbohu where is CI? I don't see any CI being performed on this PR either via https://github.com/greenelab/hetmech-backend/pull/15 or https://circleci.com/gh/greenelab/hetmech-backend.

Sid note: we should add a CI badge to README.

**Comment by dongbohu** [comment]
CircleCI is only enabled in greenelab/hetmech-backend (including all
branches). You have to enable it in your own fork too.

**Comment by dhimmel** [comment]
I just switched this "advanced" CircleCI setting on:

> Build forked pull requests
Run builds for pull requests from forks. CircleCI will automatically update the commit status shown on GitHub's pull request page.

IMO the most important purpose of CI is to build pull requests such that we don't end up merging faulty code. I am shocked this feature is not enabled by default.

**Comment by cgreene** [comment]
@dhimmel : do you store any secrets in environment variables / etc that could get written out? Some CI services expose that to the build environment that runs PRs. That means anyone who files a PR could extract those secrets. I'm not sure 1) if this repo uses anything like that to automate deployment; 2) Circle CI has protection for this.

**Comment by dhimmel** [comment]
PR builds now seem to be working. Although it looks like it's just building the commit rather than the commit merged into the current master (which IMO is slightly preferable).

> do you store any secrets in environment variables / etc that could get written out?

I don't think so. We define [public secrets](https://github.com/greenelab/hetmech-backend/blob/ca2e6bee390b2dff419b0918c547f66b874b2e61/.circleci/ci_secrets.yml) for CircleCI. Of course, secrets shouldn't be available to PR builds. Haven't checked CircleCI's behavior here.

**Review by dongbohu — APPROVED** [review]

**Comment by dhimmel** [comment]
After deleting and recreating the `dj_hetmech` database as per https://github.com/greenelab/hetmech-backend/issues/16, the import succeeded with the following output:
 
```
>>> python manage.py populate_database --max-metapath-length=3  --reduced-metapaths --batch-size=12000

_download_hetionet_hetmat(self=<dj_hetmech_app.management.commands.populate_database.Command object at 0x7f9a810e8320>) ran in 0:00:00
_hetionet_graph(self=<dj_hetmech_app.management.commands.populate_database.Command object at 0x7f9a810e8320>) ran in 0:01:02
_populate_metanode_table() ran in 0:00:00
_populate_node_table() ran in 0:00:08
_populate_metapath_table() ran in 0:00:00
_download_path_counts(length=1) ran in 0:00:00
_populate_degree_grouped_permutation_table(length=1) ran in 0:00:00
_download_path_counts(length=2) ran in 0:00:01
_populate_degree_grouped_permutation_table(length=2) ran in 0:00:03
_download_path_counts(length=3) ran in 0:00:02
_populate_degree_grouped_permutation_table(length=3) ran in 0:00:34
_populate_path_count_table() ran in 0:19:43
```

@ben-heil [reports](https://github.com/greenelab/hetmech/issues/153#issuecomment-460748437) the zero p-values due to imprecision are no longer in the database. Will merge this PR.

**Pull request merged**
