### PR TITLE
nodes endpoint: search against a node and report n_metapaths 

### PR DESCRIPTION
**Pull request by dhimmel**

### CODE REVIEW

**Comment by dhimmel** [comment]
As of https://github.com/greenelab/hetmech-backend/pull/51/commits/eb045c88ca74baf6aa8ea8e2699862d86f455141, the following output is returned for `http://localhost:8000/v1/nodes/?count_metapaths_to=5`:

```json
        {
            "id": 4,
            "metapath_count": 1,
            "identifier": "GO:0045833",
            "identifier_type": "str",
            "name": "negative regulation of lipid metabolic process",
            "properties": {
                "url": "http://purl.obolibrary.org/obo/GO_0045833",
                "source": "Gene Ontology",
                "license": "CC BY 4.0"
            },
            "metanode": "Biological Process"
        },
```

When `count_metapaths_to` is not specified, then `metapath_count` is blank. I would prefer if it were removed entirely in that case and will discuss with @dongbohu. Thanks @dongbohu for the help to get thus far.

**Comment by dongbohu** [comment]
@dhimmel, add a constructor into `NodeSerializer` class, like this:
```
class NodeSerializer(serializers.ModelSerializer):
    def __init__(self, *args, **kwargs):
        super(NodeSerializer, self).__init__(*args, **kwargs)
        request = self.context.get("request")
        if not request or 'count_metapaths_to' not in request.query_params:
            self.fields.pop('metapath_count')
    ... ...
```
see whether `metapath_count` field will disappear when `count_metapaths_to` is not specified.

**Comment by dhimmel** [comment]
We also need to look into sorting the results by `metapath_count` and potentially other factors.

**Comment by dongbohu** [comment]
@dhimmel, here is a revised `NodeViewSet` to give error response when `count_metapaths_to` is not a number:
```
class NodeViewSet(ReadOnlyModelViewSet):
    """
    Return nodes in the network that match the search term (sometimes partially).
    Use `count_metapaths_to=node_id` to return non-null values for metapath_counts.
    """
    http_method_names = ['get']
    serializer_class = NodeSerializer
    filter_backends = (filters.SearchFilter, )
    # See the following page for "search" implementation and other filter options:
    # https://www.django-rest-framework.org/api-guide/filtering/
    search_fields = ('identifier', 'metanode__identifier', 'name')

    def get_serializer_context(self):
        """
        Add metapath_counts to context if "count_metapaths_to" was specified.
        https://stackoverflow.com/a/52859696/4651668
        """
        context = super().get_serializer_context()
        search_against = context['request'].query_params.get('count_metapaths_to')
        if search_against is None:
            return context
        try:
            search_against = int(search_against)
        except ValueError:
            return context

        from dj_hetmech_app.utils.paths import get_metapath_counts_for_node
        context['metapath_counts'] = get_metapath_counts_for_node(search_against)
        return context

    def get_queryset(self):
        """Optionally restricts the returned nodes to a given list of
        metanode abbreviations by filtering against a comma-separated
        `metanodes` query parameter in the URL.
        """

        queryset = Node.objects.all()
        if 'count_metapaths_to' in self.request.query_params:
            if not self.request.query_params.get('count_metapaths_to').isdigit():
                return None

        metanodes_str = self.request.query_params.get('metanodes', None)
        if metanodes_str is not None:
            metanodes = metanodes_str.split(',')
            queryset = queryset.filter(metanode__abbreviation__in=metanodes)

        return queryset

    def list(self, request):
        queryset = self.get_queryset()
        if queryset is None:
            return Response(
                {'error': 'count_metapaths_to is not a valid number'},
                status=status.HTTP_400_BAD_REQUEST
            )

        data = NodeSerializer(get_queryset, many=True).data
        context = {
            "data" : data,
            "message" : "Contents returned successfully",
            "success" : True
        }
        return Response(context, status=status.HTTP_200_OK)
```
Try it and see whether this is what you want.

**Comment by dongbohu** [comment]
About sorting the results, why not let the frontend handle it? It will be just a few lines of extra code.

**Comment by dhimmel** [comment]
The method in https://github.com/greenelab/hetmech-backend/pull/51#issuecomment-493149816 destroys pagination causing a massive JSON response for queries like http://localhost:8000/v1/nodes/?count_metapaths_to=34000.

> About sorting the results, why not let the frontend handle it?

Because the frontend receives only a small subset of all the matches when there are many matches due to pagination. Sorting therefore should happen on backend.

**Comment by dhimmel** [comment]
@dongbohu this is now ready for review.

http://localhost:8000/v1/count-metapaths-to/999/ returns results like:

```
{
    "query-node": 999,
    "count": 2841,
    "max-nodes": 50,
    "results": [
        {
            "id": 38340,
            "identifier": "DB01234",
            "identifier_type": "str",
            "name": "Dexamethasone",
            "properties": {
                "url": "http://www.drugbank.ca/drugs/DB01234",
                "inchi": "InChI=1S/C22H29FO5/c1-12-8-16-15-5-4-13-9-14(25)6-7-19(13,2)21(15,23)17(26)10-20(16,3)22(12,28)18(27)11-24/h6-7,9,12,15-17,24,26,28H,4-5,8,10-11H2,1-3H3/t12-,15+,16+,17+,19+,20+,21+,22+/m1/s1",
                "source": "DrugBank",
                "license": "CC BY-NC 4.0",
                "inchikey": "InChIKey=UREBDLICKHMUKA-CXSFZGCWSA-N"
            },
            "metanode": "Compound",
            "metapath_count": 8
        },
        {
            "id": 43519,
            "identifier": "DB01047",
            "identifier_type": "str",
            "name": "Fluocinonide",
            "properties": {
                "url": "http://www.drugbank.ca/drugs/DB01047",
                "inchi": "InChI=1S/C26H32F2O7/c1-13(29)33-12-20(32)26-21(34-22(2,3)35-26)10-15-16-9-18(27)17-8-14(30)6-7-23(17,4)25(16,28)19(31)11-24(15,26)5/h6-8,15-16,18-19,21,31H,9-12H2,1-5H3/t15-,16-,18-,19-,21+,23-,24-,25-,26+/m0/s1",
                "source": "DrugBank",
                "license": "CC BY-NC 4.0",
                "inchikey": "InChIKey=WJOHZNCJWYWUJD-IUGZLZTKSA-N"
            },
            "metanode": "Compound",
            "metapath_count": 8
        },
```

**Review by dongbohu — APPROVED** [review]

**Pull request merged**
