### PR TITLE
increase amount of database to populate

### PR DESCRIPTION
**Pull request by dhimmel**

### CODE REVIEW

**Comment by dhimmel** [comment]
Populating the _reduced_ database took about 5 hours to load a local postgres container based on https://github.com/greenelab/hetmech-backend/pull/41/commits/018bc89893998ad2d16703b2143e8449cbc0602b:

```
python manage.py populate_database --max-metapath-length=3  --reduced-metapaths --batch-size=12000

_download_hetionet_hetmat(self=<dj_hetmech_app.management.commands.populate_database.Command object at 0x7ffbdeefcd68>) ran in 0:00:00
_populate_metanode_table() ran in 0:00:00
_populate_node_table() ran in 0:00:08
_populate_metapath_table() ran in 0:00:00
_download_path_counts(length=1) ran in 0:00:00
_populate_degree_grouped_permutation_table(length=1) ran in 0:00:01
_download_path_counts(length=2) ran in 0:00:00
_populate_degree_grouped_permutation_table(length=2) ran in 0:01:47
_download_path_counts(length=3) ran in 0:00:06
_populate_degree_grouped_permutation_table(length=3) ran in 0:08:44
_populate_path_count_table() ran in 5:00:27
```

Note that uploading to the cloud database takes much longer. As per `du --human-readable --summarize database`, the database is 16 GB. The `database_info` management command, shows that the database contains 1,014 metapaths.

<details>
<summary>database info</summary>

```
python manage.py database_info

################################ Metanode Table ################################
11 rows

         identifier abbreviation  n_nodes
            Anatomy            A      402
 Biological Process           BP    11381
 Cellular Component           CC     1391
           Compound            C     1552
            Disease            D      137 

################################## Node Table ##################################
47,031 rows

 id         metanode_id  identifier identifier_type                                            name                                               data
  0                Gene      128239             int                                          IQGAP3  {'url': 'http://identifiers.org/ncbigene/12823...
  1         Side Effect    C1112256             str              Peripheral sensorimotor neuropathy  {'url': 'http://identifiers.org/umls/C1112256'...
  2  Biological Process  GO:0097343             str                            ripoptosome assembly  {'url': 'http://purl.obolibrary.org/obo/GO_009...
  3  Molecular Function  GO:0003884             str                   D-amino-acid oxidase activity  {'url': 'http://purl.obolibrary.org/obo/GO_000...
  4  Biological Process  GO:0045833             str  negative regulation of lipid metabolic process  {'url': 'http://purl.obolibrary.org/obo/GO_004... 

################################ Metapath Table ################################
1,014 rows

abbreviation                                   name source_id            target_id  length  path_count_density  path_count_mean  path_count_max  dwpc_raw_mean
         AlD              Anatomy–localizes–Disease   Anatomy              Disease       1            0.065403         0.065403               1       0.003746
         CrC            Compound–resembles–Compound  Compound             Compound       1            0.005385         0.005385               1       0.000500
         CpD             Compound–palliates–Disease  Compound              Disease       1            0.001834         0.001834               1       0.000417
         CtD                Compound–treats–Disease  Compound              Disease       1            0.003551         0.003551               1       0.000633
        CiPC  Compound–includes–Pharmacologic Class  Compound  Pharmacologic Class       1            0.001922         0.001922               1       0.000798 

######################## DegreeGroupedPermutation Table ########################
5,896,378 rows

 id metapath_id  source_degree  target_degree  n_dwpcs  n_nonzero_dwpcs  nonzero_mean  nonzero_sd
  1         AlD              0              0     3200                0           NaN         NaN
  2         AlD              0              4     2400                0           NaN         NaN
  3         AlD              0              6     4000                0           NaN         NaN
  4         AlD              0              7      800                0           NaN         NaN
  5         AlD              0              8     4800                0           NaN         NaN 

############################### PathCount Table ################################
40,616,701 rows

 id metapath_id  source_id  target_id   dgp_id  path_count      dwpc   p_value
  1    DlAdGr>G       2961       6325  5044644           1  2.620610  0.007621
  2    DlAdGr>G       2961       9710  5044646           1  1.691002  0.076972
  3    DlAdGr>G       2961      13702  5044644           1  2.033113  0.030933
  4    DlAdGr>G       2961      22322  5044854          35  3.354054  0.071749
  5    DlAdGr>G       2961       8134  5044646           2  2.236929  0.025600 

1,014 completed metapaths of 1,014 total metapaths
```

</details>

**Comment by dhimmel** [comment]
Local import based on https://github.com/greenelab/hetmech-backend/pull/41/commits/21a245f8017d2280e28054c2ff4661f44f4f7ac9 succeeded:

```
python manage.py populate_database --max-metapath-length=3 --batch-size=12000
_download_hetionet_hetmat(self=<dj_hetmech_app.management.commands.populate_database.Command object at 0x7f4ffd1e9fd0>) ran in 0:00:00
_populate_metanode_table() ran in 0:00:00
_populate_node_table() ran in 0:00:08
_populate_metapath_table() ran in 0:00:00
_download_path_counts(length=1) ran in 0:00:01
_populate_degree_grouped_permutation_table(length=1) ran in 0:01:06
_download_path_counts(length=2) ran in 0:03:31
_populate_degree_grouped_permutation_table(length=2) ran in 0:09:56
_download_path_counts(length=3) ran in 0:44:11
_populate_degree_grouped_permutation_table(length=3) ran in 0:57:51
_populate_path_count_table() ran in 3 days, 13:48:21
```

Database is 66 GB with 174,986,768 path counts rows.

<details>
<summary>database_info</summary>

```
python manage.py database_info
################################ Metanode Table ################################
11 rows

         identifier abbreviation  n_nodes
            Anatomy            A      402
 Biological Process           BP    11381
 Cellular Component           CC     1391
           Compound            C     1552
            Disease            D      137 

################################## Node Table ##################################
47,031 rows

 id         metanode_id  identifier identifier_type                                            name                                               data
  0                Gene      128239             int                                          IQGAP3  {'url': 'http://identifiers.org/ncbigene/12823...
  1         Side Effect    C1112256             str              Peripheral sensorimotor neuropathy  {'url': 'http://identifiers.org/umls/C1112256'...
  2  Biological Process  GO:0097343             str                            ripoptosome assembly  {'url': 'http://purl.obolibrary.org/obo/GO_009...
  3  Molecular Function  GO:0003884             str                   D-amino-acid oxidase activity  {'url': 'http://purl.obolibrary.org/obo/GO_000...
  4  Biological Process  GO:0045833             str  negative regulation of lipid metabolic process  {'url': 'http://purl.obolibrary.org/obo/GO_004... 

################################ Metapath Table ################################
2,205 rows

abbreviation                                  name           source_id target_id  length  path_count_density  path_count_mean  path_count_max  dwpc_raw_mean  n_similar  p_threshold
         AlD             Anatomy–localizes–Disease             Anatomy   Disease       1            0.065403         0.065403               1       0.003746          1          1.0
         AdG            Anatomy–downregulates–Gene             Anatomy      Gene       1            0.012143         0.012143               1       0.000078          3          1.0
         AeG                Anatomy–expresses–Gene             Anatomy      Gene       1            0.062520         0.062520               1       0.000141          3          1.0
         AuG              Anatomy–upregulates–Gene             Anatomy      Gene       1            0.011621         0.011621               1       0.000083          3          1.0
        BPpG  Biological Process–participates–Gene  Biological Process      Gene       1            0.002347         0.002347               1       0.000031          1          1.0 

######################## DegreeGroupedPermutation Table ########################
37,905,389 rows

 id metapath_id  source_degree  target_degree    n_dwpcs  n_nonzero_dwpcs  nonzero_mean  nonzero_sd
  1         AdG              0              0  428073600                0           NaN         NaN
  2         AdG              0              1  115216800                0           NaN         NaN
  3         AdG              0              2  114558000                0           NaN         NaN
  4         AdG              0              3  104676000                0           NaN         NaN
  5         AdG              0              4  103212000                0           NaN         NaN 

############################### PathCount Table ################################
174,986,768 rows

 id metapath_id  source_id  target_id    dgp_id  path_count      dwpc   p_value
  1     CbGdDpS      40959       3076  21798466           1  4.168708  0.003379
  2     CbGdDpS      41016      26706  21798711           1  4.462495  0.003627
  3     CbGdDpS      41016      44771  21798711           1  4.248844  0.004612
  4     CbGdDpS      26947      38200  21798684           2  5.053734  0.003806
  5     CbGdDpS      26947      18692  21798676           1  4.478117  0.003615 

2,192 completed metapaths of 2,205 total metapaths
```
<details>

**Comment by dhimmel** [comment]
Testing queries for a local `runserver`:

+ http://localhost:8000/v1/query-metapaths/?source=43315&target=6215
+ http://localhost:8000/v1/query-metapaths/?source=6215&target=43315
+ http://localhost:8000/v1/query-paths/?source=43315&target=6215&metapath=CcSEcCtD
+ http://localhost:8000/v1/query-paths/?source=6215&target=43315&metapath=DtCcSEcC

**Comment by dhimmel** [comment]
## Database Dump

Command to dump database to a file ([docs](https://www.postgresql.org/docs/11/app-pgdump.html)):

```
docker exec dj_hetmech_db \
  pg_dump \
  --host=localhost --username=dj_hetmech --dbname=dj_hetmech \
  --create --clean \
  --compress=8 \
  > hetmech-pg_dump.sql.gz
```

And the output file is not too big at all!

```
du --human-readable hetmech-pg_dump.sql.gz
5.7G	hetmech-pg_dump.sql.gz
```

To import the dump to a database, I am using:

```
zcat hetmech-pg_dump.sql.gz | psql --user=dj_hetmech --dbname=dj_hetmech --host=HOST
```

**Review by dongbohu — APPROVED** [review]

**Pull request merged**
