### PR TITLE
querypair API: add metaedges field

### PR DESCRIPTION
**Pull request by dhimmel**
For machine-readability of a metapath

### CODE REVIEW

**Comment by dhimmel** [comment]
See `metaedges` below:

```json
{
   "path_counts":[
      {
         "id":150311,
         "path_count":244,
         "dwpc":2.76953131012329,
         "p_value":0.0015411045586865,
         "source_degree":30,
         "target_degree":37,
         "n_dwpcs":600,
         "n_nonzero_dwpcs":600,
         "nonzero_mean":1.48563890548344,
         "nonzero_sd":0.357956995841383,
         "reversed":false,
         "metapath_abbreviation":"CbGeAlD",
         "metapath_name":"Compound–binds–Gene–expresses–Anatomy–localizes–Disease",
         "metaedges":[
            [
               "Compound",
               "Gene",
               "binds",
               "both"
            ],
            [
               "Gene",
               "Anatomy",
               "expresses",
               "both"
            ],
            [
               "Anatomy",
               "Disease",
               "localizes",
               "both"
            ]
         ]
      },
```

**Review by dongbohu — APPROVED** [review]

**Comment by dhimmel** [comment]
@dongbohu I forgot to mention that this probably means we can remove the Metapath serializer because now we only need the abbreviation which is the primary key. But probably not a big deal to keep this?

**Comment by dongbohu** [comment]
@dhimmel That's a good point. You want to file another PR to remove it?

**Comment by dhimmel** [comment]
I am a bit indifferent. How about next time we're editing the code, we deal with it.

**Comment by dongbohu** [comment]
Let me include it in the PR that I am working on now.

**Pull request merged**
